export const subjects = [
  { value: "antiques", label: "Antiques" },
  { value: "architecture", label: "Architecture" },
  { value: "art", label: "Art" },
  { value: "bibles", label: "Bibles" },
  { value: "biography", label: "Biography" },
  { value: "business", label: "Business" },
  { value: "comics", label: "Comics" },
  { value: "computers", label: "Computers" },
  { value: "cooking", label: "Cooking" },
  { value: "crime", label: "True crime" },
  { value: "design", label: "Design" },
  { value: "drama", label: "Drama" },
  { value: "education", label: "Education" },
  { value: "family & relationships", label: "Family & relationships" },
  { value: "fiction", label: "Fiction" },
  { value: "games & activities", label: "Games & activities" },
  { value: "gardening", label: "Gardening" },
  { value: "health & fitness", label: "Health & fitness" },
  { value: "history", label: "History" },
  { value: "house & home", label: "House & home" },
  { value: "humor", label: "Humor" },
  { value: "language arts & disciplines", label: "Language arts & disciplines" },
  { value: "law", label: "Law" },
  { value: "mathematics", label: "Mathematics" },
  { value: "medical", label: "Medical" },
  { value: "music", label: "Music" },
  { value: "nature", label: "Nature" },
  { value: "pets", label: "Pets" },
  { value: "philosophy", label: "Philosophy" },
  { value: "photography", label: "Photography" },
  { value: "poetry", label: "Poetry" },
  { value: "psychology", label: "Psychology" },
  { value: "reference", label: "Reference" },
  { value: "religion", label: "Religion" },
  { value: "science", label: "Science" },
  { value: "self-help", label: "Self-help" },
  { value: "sports & recreation", label: "Sports & recreation" },
  { value: "study aids", label: "Study aids" },
  { value: "technology & engineering", label: "Technology & engineering" },
  { value: "transportation", label: "Transportation" },
  { value: "travel", label: "Travel" },
];
